// Generated by gencpp from file bd1_environment_interface/GetStateAndRewardResponse.msg
// DO NOT EDIT!


#ifndef BD1_ENVIRONMENT_INTERFACE_MESSAGE_GETSTATEANDREWARDRESPONSE_H
#define BD1_ENVIRONMENT_INTERFACE_MESSAGE_GETSTATEANDREWARDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <bd1_environment_interface/State.h>

namespace bd1_environment_interface
{
template <class ContainerAllocator>
struct GetStateAndRewardResponse_
{
  typedef GetStateAndRewardResponse_<ContainerAllocator> Type;

  GetStateAndRewardResponse_()
    : state()
    , reward(0.0)
    , episode_end(false)  {
    }
  GetStateAndRewardResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , reward(0.0)
    , episode_end(false)  {
  (void)_alloc;
    }



   typedef  ::bd1_environment_interface::State_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef double _reward_type;
  _reward_type reward;

   typedef uint8_t _episode_end_type;
  _episode_end_type episode_end;





  typedef boost::shared_ptr< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetStateAndRewardResponse_

typedef ::bd1_environment_interface::GetStateAndRewardResponse_<std::allocator<void> > GetStateAndRewardResponse;

typedef boost::shared_ptr< ::bd1_environment_interface::GetStateAndRewardResponse > GetStateAndRewardResponsePtr;
typedef boost::shared_ptr< ::bd1_environment_interface::GetStateAndRewardResponse const> GetStateAndRewardResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator1> & lhs, const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.reward == rhs.reward &&
    lhs.episode_end == rhs.episode_end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator1> & lhs, const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bd1_environment_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4311283603913f545c123b92fee5b5c";
  }

  static const char* value(const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4311283603913f5ULL;
  static const uint64_t static_value2 = 0x45c123b92fee5b5cULL;
};

template<class ContainerAllocator>
struct DataType< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd1_environment_interface/GetStateAndRewardResponse";
  }

  static const char* value(const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd1_environment_interface/State state\n"
"float64 reward\n"
"bool episode_end\n"
"\n"
"\n"
"================================================================================\n"
"MSG: bd1_environment_interface/State\n"
"float64 up_p_r\n"
"float64 up_p_l\n"
"float64 mid_p_r\n"
"float64 mid_p_l\n"
"float64 feet_p_r\n"
"float64 feet_p_l\n"
"\n"
"#float64 up_v_r\n"
"#float64 up_v_l\n"
"#float64 mid_v_r\n"
"#float64 mid_v_l\n"
"#float64 feet_v_r\n"
"float64 feet_v_l\n"
"\n"
"float64 neck_p\n"
"#float64 neck_v\n"
"float64 head_p\n"
"#float64 head_v\n"
"\n"
"float64 pose_x\n"
"float64 pose_y\n"
"float64 pose_z\n"
"float64 rot_r\n"
"float64 rot_p\n"
"float64 rot_y\n"
"\n"
;
  }

  static const char* value(const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.reward);
      stream.next(m.episode_end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetStateAndRewardResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bd1_environment_interface::GetStateAndRewardResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::bd1_environment_interface::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "reward: ";
    Printer<double>::stream(s, indent + "  ", v.reward);
    s << indent << "episode_end: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.episode_end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BD1_ENVIRONMENT_INTERFACE_MESSAGE_GETSTATEANDREWARDRESPONSE_H
