// Generated by gencpp from file bd1_environment_interface/GetVectStateAndReward.msg
// DO NOT EDIT!


#ifndef BD1_ENVIRONMENT_INTERFACE_MESSAGE_GETVECTSTATEANDREWARD_H
#define BD1_ENVIRONMENT_INTERFACE_MESSAGE_GETVECTSTATEANDREWARD_H

#include <ros/service_traits.h>


#include <bd1_environment_interface/GetVectStateAndRewardRequest.h>
#include <bd1_environment_interface/GetVectStateAndRewardResponse.h>


namespace bd1_environment_interface
{

struct GetVectStateAndReward
{

typedef GetVectStateAndRewardRequest Request;
typedef GetVectStateAndRewardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetVectStateAndReward
} // namespace bd1_environment_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bd1_environment_interface::GetVectStateAndReward > {
  static const char* value()
  {
    return "d2372a06335f71544d81aba4da8f6263";
  }

  static const char* value(const ::bd1_environment_interface::GetVectStateAndReward&) { return value(); }
};

template<>
struct DataType< ::bd1_environment_interface::GetVectStateAndReward > {
  static const char* value()
  {
    return "bd1_environment_interface/GetVectStateAndReward";
  }

  static const char* value(const ::bd1_environment_interface::GetVectStateAndReward&) { return value(); }
};


// service_traits::MD5Sum< ::bd1_environment_interface::GetVectStateAndRewardRequest> should match
// service_traits::MD5Sum< ::bd1_environment_interface::GetVectStateAndReward >
template<>
struct MD5Sum< ::bd1_environment_interface::GetVectStateAndRewardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bd1_environment_interface::GetVectStateAndReward >::value();
  }
  static const char* value(const ::bd1_environment_interface::GetVectStateAndRewardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bd1_environment_interface::GetVectStateAndRewardRequest> should match
// service_traits::DataType< ::bd1_environment_interface::GetVectStateAndReward >
template<>
struct DataType< ::bd1_environment_interface::GetVectStateAndRewardRequest>
{
  static const char* value()
  {
    return DataType< ::bd1_environment_interface::GetVectStateAndReward >::value();
  }
  static const char* value(const ::bd1_environment_interface::GetVectStateAndRewardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bd1_environment_interface::GetVectStateAndRewardResponse> should match
// service_traits::MD5Sum< ::bd1_environment_interface::GetVectStateAndReward >
template<>
struct MD5Sum< ::bd1_environment_interface::GetVectStateAndRewardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bd1_environment_interface::GetVectStateAndReward >::value();
  }
  static const char* value(const ::bd1_environment_interface::GetVectStateAndRewardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bd1_environment_interface::GetVectStateAndRewardResponse> should match
// service_traits::DataType< ::bd1_environment_interface::GetVectStateAndReward >
template<>
struct DataType< ::bd1_environment_interface::GetVectStateAndRewardResponse>
{
  static const char* value()
  {
    return DataType< ::bd1_environment_interface::GetVectStateAndReward >::value();
  }
  static const char* value(const ::bd1_environment_interface::GetVectStateAndRewardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BD1_ENVIRONMENT_INTERFACE_MESSAGE_GETVECTSTATEANDREWARD_H
