// Generated by gencpp from file bd1_environment_interface/SetAction.msg
// DO NOT EDIT!


#ifndef BD1_ENVIRONMENT_INTERFACE_MESSAGE_SETACTION_H
#define BD1_ENVIRONMENT_INTERFACE_MESSAGE_SETACTION_H

#include <ros/service_traits.h>


#include <bd1_environment_interface/SetActionRequest.h>
#include <bd1_environment_interface/SetActionResponse.h>


namespace bd1_environment_interface
{

struct SetAction
{

typedef SetActionRequest Request;
typedef SetActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAction
} // namespace bd1_environment_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bd1_environment_interface::SetAction > {
  static const char* value()
  {
    return "971ec173ddadd49b8b050bf728686fd8";
  }

  static const char* value(const ::bd1_environment_interface::SetAction&) { return value(); }
};

template<>
struct DataType< ::bd1_environment_interface::SetAction > {
  static const char* value()
  {
    return "bd1_environment_interface/SetAction";
  }

  static const char* value(const ::bd1_environment_interface::SetAction&) { return value(); }
};


// service_traits::MD5Sum< ::bd1_environment_interface::SetActionRequest> should match
// service_traits::MD5Sum< ::bd1_environment_interface::SetAction >
template<>
struct MD5Sum< ::bd1_environment_interface::SetActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bd1_environment_interface::SetAction >::value();
  }
  static const char* value(const ::bd1_environment_interface::SetActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bd1_environment_interface::SetActionRequest> should match
// service_traits::DataType< ::bd1_environment_interface::SetAction >
template<>
struct DataType< ::bd1_environment_interface::SetActionRequest>
{
  static const char* value()
  {
    return DataType< ::bd1_environment_interface::SetAction >::value();
  }
  static const char* value(const ::bd1_environment_interface::SetActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bd1_environment_interface::SetActionResponse> should match
// service_traits::MD5Sum< ::bd1_environment_interface::SetAction >
template<>
struct MD5Sum< ::bd1_environment_interface::SetActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bd1_environment_interface::SetAction >::value();
  }
  static const char* value(const ::bd1_environment_interface::SetActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bd1_environment_interface::SetActionResponse> should match
// service_traits::DataType< ::bd1_environment_interface::SetAction >
template<>
struct DataType< ::bd1_environment_interface::SetActionResponse>
{
  static const char* value()
  {
    return DataType< ::bd1_environment_interface::SetAction >::value();
  }
  static const char* value(const ::bd1_environment_interface::SetActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BD1_ENVIRONMENT_INTERFACE_MESSAGE_SETACTION_H
