(cl:in-package bd1_environment_interface-msg)
(cl:export '(UP_P_R-VAL
          UP_P_R
          UP_P_L-VAL
          UP_P_L
          MID_P_R-VAL
          MID_P_R
          MID_P_L-VAL
          MID_P_L
          FEET_P_R-VAL
          FEET_P_R
          FEET_P_L-VAL
          FEET_P_L
          FEET_V_L-VAL
          FEET_V_L
          NECK_P-VAL
          NECK_P
          HEAD_P-VAL
          HEAD_P
          POSE_X-VAL
          POSE_X
          POSE_Y-VAL
          POSE_Y
          POSE_Z-VAL
          POSE_Z
          ROT_R-VAL
          ROT_R
          ROT_P-VAL
          ROT_P
          ROT_Y-VAL
          ROT_Y
))