// Generated by gencpp from file bd1_gazebo_env_interface/ResetResponse.msg
// DO NOT EDIT!


#ifndef BD1_GAZEBO_ENV_INTERFACE_MESSAGE_RESETRESPONSE_H
#define BD1_GAZEBO_ENV_INTERFACE_MESSAGE_RESETRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bd1_gazebo_env_interface
{
template <class ContainerAllocator>
struct ResetResponse_
{
  typedef ResetResponse_<ContainerAllocator> Type;

  ResetResponse_()
    : state()  {
    }
  ResetResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetResponse_

typedef ::bd1_gazebo_env_interface::ResetResponse_<std::allocator<void> > ResetResponse;

typedef boost::shared_ptr< ::bd1_gazebo_env_interface::ResetResponse > ResetResponsePtr;
typedef boost::shared_ptr< ::bd1_gazebo_env_interface::ResetResponse const> ResetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator1> & lhs, const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator1> & lhs, const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bd1_gazebo_env_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c30e6364d50c603d25671fea66595c53";
  }

  static const char* value(const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc30e6364d50c603dULL;
  static const uint64_t static_value2 = 0x25671fea66595c53ULL;
};

template<class ContainerAllocator>
struct DataType< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd1_gazebo_env_interface/ResetResponse";
  }

  static const char* value(const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] state\n"
"\n"
;
  }

  static const char* value(const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bd1_gazebo_env_interface::ResetResponse_<ContainerAllocator>& v)
  {
    s << indent << "state[]" << std::endl;
    for (size_t i = 0; i < v.state.size(); ++i)
    {
      s << indent << "  state[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BD1_GAZEBO_ENV_INTERFACE_MESSAGE_RESETRESPONSE_H
