// Generated by gencpp from file bd1_train/SaveAgentResponse.msg
// DO NOT EDIT!


#ifndef BD1_TRAIN_MESSAGE_SAVEAGENTRESPONSE_H
#define BD1_TRAIN_MESSAGE_SAVEAGENTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bd1_train
{
template <class ContainerAllocator>
struct SaveAgentResponse_
{
  typedef SaveAgentResponse_<ContainerAllocator> Type;

  SaveAgentResponse_()
    : directory_path()  {
    }
  SaveAgentResponse_(const ContainerAllocator& _alloc)
    : directory_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _directory_path_type;
  _directory_path_type directory_path;





  typedef boost::shared_ptr< ::bd1_train::SaveAgentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bd1_train::SaveAgentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SaveAgentResponse_

typedef ::bd1_train::SaveAgentResponse_<std::allocator<void> > SaveAgentResponse;

typedef boost::shared_ptr< ::bd1_train::SaveAgentResponse > SaveAgentResponsePtr;
typedef boost::shared_ptr< ::bd1_train::SaveAgentResponse const> SaveAgentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bd1_train::SaveAgentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bd1_train::SaveAgentResponse_<ContainerAllocator1> & lhs, const ::bd1_train::SaveAgentResponse_<ContainerAllocator2> & rhs)
{
  return lhs.directory_path == rhs.directory_path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bd1_train::SaveAgentResponse_<ContainerAllocator1> & lhs, const ::bd1_train::SaveAgentResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bd1_train

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bd1_train::SaveAgentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bd1_train::SaveAgentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bd1_train::SaveAgentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90dcb560b000b228109ef2e71a0336c1";
  }

  static const char* value(const ::bd1_train::SaveAgentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90dcb560b000b228ULL;
  static const uint64_t static_value2 = 0x109ef2e71a0336c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd1_train/SaveAgentResponse";
  }

  static const char* value(const ::bd1_train::SaveAgentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string directory_path\n"
"\n"
;
  }

  static const char* value(const ::bd1_train::SaveAgentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.directory_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveAgentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bd1_train::SaveAgentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bd1_train::SaveAgentResponse_<ContainerAllocator>& v)
  {
    s << indent << "directory_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.directory_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BD1_TRAIN_MESSAGE_SAVEAGENTRESPONSE_H
