// Generated by gencpp from file bd1_train/SaveAgent.msg
// DO NOT EDIT!


#ifndef BD1_TRAIN_MESSAGE_SAVEAGENT_H
#define BD1_TRAIN_MESSAGE_SAVEAGENT_H

#include <ros/service_traits.h>


#include <bd1_train/SaveAgentRequest.h>
#include <bd1_train/SaveAgentResponse.h>


namespace bd1_train
{

struct SaveAgent
{

typedef SaveAgentRequest Request;
typedef SaveAgentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveAgent
} // namespace bd1_train


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bd1_train::SaveAgent > {
  static const char* value()
  {
    return "641c24cd18aefc7a57649fc1a8a53333";
  }

  static const char* value(const ::bd1_train::SaveAgent&) { return value(); }
};

template<>
struct DataType< ::bd1_train::SaveAgent > {
  static const char* value()
  {
    return "bd1_train/SaveAgent";
  }

  static const char* value(const ::bd1_train::SaveAgent&) { return value(); }
};


// service_traits::MD5Sum< ::bd1_train::SaveAgentRequest> should match
// service_traits::MD5Sum< ::bd1_train::SaveAgent >
template<>
struct MD5Sum< ::bd1_train::SaveAgentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bd1_train::SaveAgent >::value();
  }
  static const char* value(const ::bd1_train::SaveAgentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bd1_train::SaveAgentRequest> should match
// service_traits::DataType< ::bd1_train::SaveAgent >
template<>
struct DataType< ::bd1_train::SaveAgentRequest>
{
  static const char* value()
  {
    return DataType< ::bd1_train::SaveAgent >::value();
  }
  static const char* value(const ::bd1_train::SaveAgentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bd1_train::SaveAgentResponse> should match
// service_traits::MD5Sum< ::bd1_train::SaveAgent >
template<>
struct MD5Sum< ::bd1_train::SaveAgentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bd1_train::SaveAgent >::value();
  }
  static const char* value(const ::bd1_train::SaveAgentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bd1_train::SaveAgentResponse> should match
// service_traits::DataType< ::bd1_train::SaveAgent >
template<>
struct DataType< ::bd1_train::SaveAgentResponse>
{
  static const char* value()
  {
    return DataType< ::bd1_train::SaveAgent >::value();
  }
  static const char* value(const ::bd1_train::SaveAgentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BD1_TRAIN_MESSAGE_SAVEAGENT_H
