(cl:in-package bd1_environment_interface-srv)
(cl:export '(UP_P_R-VAL
          UP_P_R
          UP_P_L-VAL
          UP_P_L
          MID_P_R-VAL
          MID_P_R
          MID_P_L-VAL
          MID_P_L
          FEET_P_R-VAL
          FEET_P_R
          FEET_P_L-VAL
          FEET_P_L
          UP_V_R-VAL
          UP_V_R
          UP_V_L-VAL
          UP_V_L
          MID_V_R-VAL
          MID_V_R
          MID_V_L-VAL
          MID_V_L
          FEET_V_R-VAL
          FEET_V_R
          FEET_V_L-VAL
          FEET_V_L
          NECK_P-VAL
          NECK_P
          NECK_V-VAL
          NECK_V
          HEAD_P-VAL
          HEAD_P
          HEAD_V-VAL
          HEAD_V
))