(cl:defpackage bd1_environment_interface-srv
  (:use )
  (:export
   "GETSTATEANDREWARD"
   "<GETSTATEANDREWARD-REQUEST>"
   "GETSTATEANDREWARD-REQUEST"
   "<GETSTATEANDREWARD-RESPONSE>"
   "GETSTATEANDREWARD-RESPONSE"
   "GETVECTSTATEANDREWARD"
   "<GETVECTSTATEANDREWARD-REQUEST>"
   "GETVECTSTATEANDREWARD-REQUEST"
   "<GETVECTSTATEANDREWARD-RESPONSE>"
   "GETVECTSTATEANDREWARD-RESPONSE"
   "SETACTION"
   "<SETACTION-REQUEST>"
   "SETACTION-REQUEST"
   "<SETACTION-RESPONSE>"
   "SETACTION-RESPONSE"
   "SETVECTACTION"
   "<SETVECTACTION-REQUEST>"
   "SETVECTACTION-REQUEST"
   "<SETVECTACTION-RESPONSE>"
   "SETVECTACTION-RESPONSE"
  ))

