# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bd1_environment_interface/GetStateAndRewardRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetStateAndRewardRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "bd1_environment_interface/GetStateAndRewardRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetStateAndRewardRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from bd1_environment_interface/GetStateAndRewardResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import bd1_environment_interface.msg

class GetStateAndRewardResponse(genpy.Message):
  _md5sum = "b4311283603913f545c123b92fee5b5c"
  _type = "bd1_environment_interface/GetStateAndRewardResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bd1_environment_interface/State state
float64 reward
bool episode_end


================================================================================
MSG: bd1_environment_interface/State
float64 up_p_r
float64 up_p_l
float64 mid_p_r
float64 mid_p_l
float64 feet_p_r
float64 feet_p_l

#float64 up_v_r
#float64 up_v_l
#float64 mid_v_r
#float64 mid_v_l
#float64 feet_v_r
float64 feet_v_l

float64 neck_p
#float64 neck_v
float64 head_p
#float64 head_v

float64 pose_x
float64 pose_y
float64 pose_z
float64 rot_r
float64 rot_p
float64 rot_y

"""
  __slots__ = ['state','reward','episode_end']
  _slot_types = ['bd1_environment_interface/State','float64','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state,reward,episode_end

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetStateAndRewardResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = bd1_environment_interface.msg.State()
      if self.reward is None:
        self.reward = 0.
      if self.episode_end is None:
        self.episode_end = False
    else:
      self.state = bd1_environment_interface.msg.State()
      self.reward = 0.
      self.episode_end = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_16dB().pack(_x.state.up_p_r, _x.state.up_p_l, _x.state.mid_p_r, _x.state.mid_p_l, _x.state.feet_p_r, _x.state.feet_p_l, _x.state.feet_v_l, _x.state.neck_p, _x.state.head_p, _x.state.pose_x, _x.state.pose_y, _x.state.pose_z, _x.state.rot_r, _x.state.rot_p, _x.state.rot_y, _x.reward, _x.episode_end))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = bd1_environment_interface.msg.State()
      end = 0
      _x = self
      start = end
      end += 129
      (_x.state.up_p_r, _x.state.up_p_l, _x.state.mid_p_r, _x.state.mid_p_l, _x.state.feet_p_r, _x.state.feet_p_l, _x.state.feet_v_l, _x.state.neck_p, _x.state.head_p, _x.state.pose_x, _x.state.pose_y, _x.state.pose_z, _x.state.rot_r, _x.state.rot_p, _x.state.rot_y, _x.reward, _x.episode_end,) = _get_struct_16dB().unpack(str[start:end])
      self.episode_end = bool(self.episode_end)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_16dB().pack(_x.state.up_p_r, _x.state.up_p_l, _x.state.mid_p_r, _x.state.mid_p_l, _x.state.feet_p_r, _x.state.feet_p_l, _x.state.feet_v_l, _x.state.neck_p, _x.state.head_p, _x.state.pose_x, _x.state.pose_y, _x.state.pose_z, _x.state.rot_r, _x.state.rot_p, _x.state.rot_y, _x.reward, _x.episode_end))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = bd1_environment_interface.msg.State()
      end = 0
      _x = self
      start = end
      end += 129
      (_x.state.up_p_r, _x.state.up_p_l, _x.state.mid_p_r, _x.state.mid_p_l, _x.state.feet_p_r, _x.state.feet_p_l, _x.state.feet_v_l, _x.state.neck_p, _x.state.head_p, _x.state.pose_x, _x.state.pose_y, _x.state.pose_z, _x.state.rot_r, _x.state.rot_p, _x.state.rot_y, _x.reward, _x.episode_end,) = _get_struct_16dB().unpack(str[start:end])
      self.episode_end = bool(self.episode_end)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_16dB = None
def _get_struct_16dB():
    global _struct_16dB
    if _struct_16dB is None:
        _struct_16dB = struct.Struct("<16dB")
    return _struct_16dB
class GetStateAndReward(object):
  _type          = 'bd1_environment_interface/GetStateAndReward'
  _md5sum = 'b4311283603913f545c123b92fee5b5c'
  _request_class  = GetStateAndRewardRequest
  _response_class = GetStateAndRewardResponse
